### ISSUE TITLE
hi how to install 

### ISSUE THREAD

**Issue by cindy563** [xulihang/ImageTrans_chrome_extension#2]
hi 
您好！怎么安装！能不能帮忙发一个视频哦！
我今天第三天了，还是不会安装，我只在chrom那里安装了插件！
（洛洛问句能有人帮忙安装吗）
QQ：695348391
微信：y695348391
邮箱：cindyclin563@gmail.com
万分感谢！！！
       cindy

**Comment by cindy563** [comment]
我把下载的拉到 扩展程序，提示
D:\Documents\Downloads\ImageTrans_wsServer (1)
错误
清单文件缺失或不可读取
无法加载清单

**Comment by xulihang** [comment]
按照这里的说明操作了吗：https://github.com/xulihang/ImageTrans_chrome_extension#%E5%AE%89%E8%A3%85

wsServer是和ImageTrans放在一起，不是和插件放一起

**Comment by cindy563** [comment]
您好！
不好意思！太笨了不会啊。。还在淘宝上问了好几个人也不会安装 都无语。。
真的醉了。。
有没有技术支持的人，远程操作的

谢谢！！！
  Cindy

Lihang Xu ***@***.***> 于2021年12月9日周四 09:29写道：

**Comment by xulihang** [comment]
你有购买ImageTrans吗，麻烦发一个订单号到：[admin@basiccat.org](mailto:admin@basiccat.org)

**Comment by cindy563** [comment]
都还没有啊， 那个哪里购买我都没有找到。。 😂😅😅

Lihang Xu ***@***.***> 于2021年12月10日周五 17:50写道：

**Comment by xulihang** [comment]
链接在这里：https://www.basiccat.org/zh/imagetrans/#%E8%8E%B7%E5%8F%96imagetrans

你想用来做什么，软件用起来有一定难度的，先评估下看看适不适合你的需求吧

**Comment by cindy563** [comment]
好！

修改产品图上的中文，改英文。。
这商业？

Lihang Xu ***@***.***> 于2021年12月13日周一 16:55写道：

**Comment by cindy563** [comment]
太菜了，我不会安装了。。
我后面实在么有办法，抠图改中文😂😅

clin cindy ***@***.***> 于2021年12月15日周三 15:56写道：
