### ISSUE TITLE
llllll

### ISSUE THREAD

**Issue by Leon516** [xulihang/ImageTrans_chrome_extension#3]
![上传95E0716F-4E23-44CE-8A8B-31E1C68D501C.jpeg...]()我上腾讯漫画网站可以 但这个网站不行 是为什么呀

**Comment by Leon516** [comment]
他显示nbad result is imagetrans running correctly

**Comment by xulihang** [comment]
链接有吗？

有的网站的图片可能没办法下载，就会报这个错误
