### ISSUE TITLE
已确保网站图片可通过另存为的方式下载，但依旧报错Bad result. Is ImageTrans running correctly?

### ISSUE THREAD

**Issue by TerenceXin** [xulihang/ImageTrans_chrome_extension#4]
![image](https://user-images.githubusercontent.com/58368436/211336521-a7d6498b-c2eb-4992-9c28-572d7c5cac2d.png)
图片所处网址为https://mangadex.org/chapter/a948e9f4-6982-48fd-953b-192b811cc30b

**Comment by xulihang** [comment]
能另存为不一定能用链接下载。mangadex的图片链接用`URL.createObjectURL`做过处理，是这样的：<blob:https://mangadex.org/ccd4af35-030a-4fdc-b0e5-b20805aa50f2>。这个目前插件还不支持

**Comment by xulihang** [comment]
可以复制图片到剪贴板，再粘贴进ImageTrans处理。

插件我会看看怎么更新下，支持这一类型的链接。

**Comment by TerenceXin** [comment]
感谢回复与及时的处理！

**Comment by xulihang** [comment]
新版的插件和ImageTrans已经可以翻译mangadex的图片了

**Comment by TerenceXin** [comment]
Good Job！
