### ISSUE TITLE
翻译有问题

### ISSUE THREAD

**Issue by cKwaming** [xulihang/ImageTrans_chrome_extension#6]
只能翻译一张，而且文字都没有了

**Comment by xulihang** [comment]
可能是没有识别出文字或者机器翻译失败了，可以换个OCR或者机器翻译。OCR在软件主界面里选，比如选baidu，机器翻译在服务器界面里修改，比如选mymemory。也有可能是项目的语言设置不对，比如需要选中文-英文。
