### ISSUE TITLE
Request: Open Source ImageTrans 

### ISSUE THREAD

**Issue by parthiv11** [xulihang/ImageTrans_chrome_extension#7]
I'm a tech enthusiast who recently discovered ImageTrans, and I've been really impressed with its capabilities. I'm eager to learn more about how it works and potentially contribute to its development. With that in mind, I kindly request that you consider open-sourcing ImageTrans. By doing so, the community would have the opportunity to access and utilize this technology, as well as collaborate to make it even better. Of course, this is just a request, and the decision is entirely up to you

By the way, I'd like to express my gratitude for creating such a fantastic tool!

**Comment by xulihang** [comment]
Making ImageTrans open source is meaningless as there won't be many contributions and I will have no economic backup.

You can start contributing to ImageTrans by writing plugins.
